### ISSUE TITLE
Two-way UDP IPC

### ISSUE THREAD

**Issue by slimshader** [Cysharp/MessagePipe#115]
How to create two-way channel when using AddMessagePipeUdpInterprocess() ? Injecting both IDistributedPublisher and IDistributedSubscriber causes error of used socket port.

ps is this boards alive at all?

**Comment by hadashiA** [comment]
Hi. Since interprocess is currently implemented in a pub/sub abstract model, it seems difficult to support bidirectional communication.
MessagePipe is specialized for unidirectional event notification, so it may be a little unsuitable for your application.
