### ISSUE TITLE
Open generic support for VContainer

### ISSUE THREAD

**Issue by notargs** [Cysharp/MessagePipe#119]
Hi,
It seems that VContainer has open generic support in 1.14.0. (https://github.com/hadashiA/VContainer/pull/367)
Are there any plans for this registration support in MessagePipe?

**Comment by hadashiA** [comment]
We added automatic injection by open generic. In [1.8.0](https://github.com/Cysharp/MessagePipe/releases/tag/1.8.0)
( NOTE: `Requesthandler` is still not  supported.

I hope you will give it a try.
Any feedback is welcome. thx!
