### ISSUE TITLE
R3 vs MessagePipe use case

### ISSUE THREAD

**Issue by man-chi** [Cysharp/MessagePipe#125]
thanks for the great contribution to such high-quality and awesome unity projects!

I also came across R3 (uniRx successor) in-memory reactive stream, can you advise on the typical use case using MessagePipe vs R3 in unity? 

my current understanding: R3 is a client async programming model connecting to MessagePipe which is a broker, and the R3 client will consume events from the messagepipe subject, is my understanding correct?

kindly help, thanks.

**Comment by neuecc** [comment]
answered at R3 repo https://github.com/Cysharp/R3/issues/194
