### ISSUE TITLE
IAsyncPublisher<T>.Publish - is it really fire-and-forget?

### ISSUE THREAD

**Issue by craigajohnson** [Cysharp/MessagePipe#32]
First off - fantastic library! Already using it in a production project.

Quick question - I have an IAsyncPublisher and am calling .Publish. If I set a breakpoint in the subscriber the Publish call is in the call stack and blocks until the subscriber completes.

Is there a configuration option necessary to make these fire-and-forget operations? The docs page indicates .Publish should be fire-and-forget.

Thank you again.

**Comment by neuecc** [comment]
Thanks for using! I'm so happy to hear that.

This is the same as Task is not always asynchronous.
If the IAsyncSubscriber is completes synchronously, it will be executed synchronously.
If you want to post the process asynchronously, you will need to explicitly `_ = Task.Run(()=>publisher.Publish())` and so on.
You can make it common by creating and attaching a filter that wrap Invoke in Task.Run.

**Comment by craigajohnson** [comment]
Perfect! I think both patterns make sense for the phrase "fire and forget" so it can be a bit ambiguous sometimes!

I'll use a filter for "QueuedFireAndForget" and maybe push that to a channel that just does up to x at a time so it does not overwhelm the threadpool with maybe thousands of tasks.

But that is adding in a pipelining pattern on top of the messaging so makes sense to not have that in MessagePipe :)
