### ISSUE TITLE
Having trouble with Scoped Services

### ISSUE THREAD

**Issue by jonathanperis** [Cysharp/MessagePipe#38]
Hi!

I've migrated my project to use MessagePipe but i have a situation that breaks me to deploy this change:

I have my Infrastructure buit with Scoped contexts and when i have to consume any IAsyncRequestHandlerCore that on the other side have a context injected that have been declared as Scoped it happens an exception:

![image](https://user-images.githubusercontent.com/13967942/120945176-77e68e00-c70e-11eb-9d16-d55da0c61000.png)

Is this a expected behavior? The actual source code is hosted here:

https://github.com/jonathanperis/cpnucleo/tree/feat-message-pipe-hellyeah

The project **Cpnucleo.Infra.Data** have the classes injected as Scoped on the **Configuration** folder (in case you adventure on investigate). The implementation of the MessagePipe is happening on the **Cpnucleo.GRPC** (consume) and **Cpnucleo.Application** (implementation)

**Comment by neuecc** [comment]
Could you configure `MessagePipeOptions.InstanceLifetime = InstanceLifetime.Scoped`?
However, I feel that Scoped is a better choice for RequestHandler, regardless of the configuration.
This may change.
However, it would be nice if you could try changing the settings first.

**Comment by jonathanperis** [comment]
i've tried and it worked successfully with `MessagePipeOptions.InstanceLifetime = InstanceLifetime.Scoped`

**Comment by neuecc** [comment]
I've released `1.5.0`.
It added `MessagePipeOptions.RequestHandlerLifetime` and default is Scoped.
InstanceLifetime no longer affects IRequestHandler/IAsyncRequestHandler.
