### ISSUE TITLE
[Suggestion] "ZenjectScope" should be fixed as "AsCached"

### ISSUE THREAD

**Issue by tsgcpp** [Cysharp/MessagePipe#55]
# MessagePipe Lifetime might not match Zenject scope
- Zenject scopes are not "Lifetime of certain Dependency Injection libs" but just "how often (or if at all) the generated instance is re-used across multiple injections".
- In Zenject, lifetimes of instances are managed by Zenject contexts (ProjectContext, SceneContext, GameObjectContext), so the lifetimes cannot be specified in binding phases of installers.

# Why Zenject scopes should be fixed as "AsCached"
- If using `AsTransient`, `IPublisher` does not connect to `ISubscriber` because the instances (including `MessageBrokerCore`) are all different.
- `AsSingle` is used to guarantee that the ResultType instance (e.g. `MessageBroker`) is single. However the ResultType classes are hided from MessagePipe users, so `AsSingle` need not to be used.
- Or if using `AsSingle`, "Zenject Identifier" feature can't be used because `AsSignle` are applied even if the ResultTypes are bound with different identifiers.

So, I think that Zenject scopes should be fixed as "AsCached".
I also make diff to fix the scope.

https://github.com/Cysharp/MessagePipe/compare/master...tsgcpp:c280f03

I would appreciate if you could give me your opinion.

**Comment by neuecc** [comment]
For practical purposes, InstanceLifetime.Scoped is AsCached, which is mostly fixed, so it's not a problem, right?
It might be better to fix it to AsCached, but I don't feel it's that essential.
Also, I don't feel the need to use terminology of Zenject.

**Comment by tsgcpp** [comment]
> For practical purposes, InstanceLifetime.Scoped is AsCached, which is mostly fixed, so it's not a problem, right?

Yes, that's right.
As far as I know, Zenject doesn't have "Scoped Lifetime" like [Microsoft.Extensions.DependencyInjection](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines) or "VContainer", so I was a little confused.
I think there is no problem if AsCached will be mostly fixed.

> It might be better to fix it to AsCached, but I don't feel it's that essential.
> Also, I don't feel the need to use terminology of Zenject.

I understand!

I appreciate your response.
