### ISSUE TITLE
publish event with delay

### ISSUE THREAD

**Issue by xracer007** [Cysharp/MessagePipe#58]
Is it possible to publish an event with a long time delay without using task.delay() from DelayRequestFilter ?

**Comment by neuecc** [comment]
Why do you want to avoid Delay?
Delay is the best choice when dealing with timers in async/await.
Also, the implementation of Delay has been optimized quite a bit in .NET 5.

**Comment by xracer007** [comment]
Thank you,i also implemented in xamarin.forms and use instead of messaging center.
Its superfast and awsome👍
