### ISSUE TITLE
`GetResult` and `UnsafeGetStatus` appears twice in Unity assets

### ISSUE THREAD

**Issue by itn3000** [Cysharp/MessagePipe#63]
# Overview

`void IUniTaskSource.GetResult(short token)` and `public IUniTaskStatus UnsafeGetStatus()` In https://github.com/Cysharp/MessagePipe/blob/7a6a2bfeae30fccd5be6e949259a02f53c92f066/src/MessagePipe.Unity/Assets/Plugins/MessagePipe/Runtime/SubscriberExtensions.FirstAsync.cs#L169-L170 appears twice when build MessagePipe.sln.

# Environment

* Windows10(x64)
* dotnet-sdk-6.0pre5
* dotnet-sdk-5.0.301

# Steps to reproduce

1. clone source
2. build by `dotnet build MessagePipe.sln`

# Expected result

* no changes will be found in git

# Additional Information

This may be caused by executing tools/PostBuildUnity/PostBuildUnity.csproj in PostBuildEvent.
This is no problem if executing only once, but executed twice, `public UniTaskStatus GetStatus(short token)` will be hit and generating same lines again.
https://github.com/Cysharp/MessagePipe/blob/7a6a2bfeae30fccd5be6e949259a02f53c92f066/tools/PostBuildUtility/Program.cs#L49-L51

**Comment by neuecc** [comment]
Thank you.
I thought it was always copied, but does that mean it's running without being copied?
Would this be solved by `SkipUnchangedFiles=false`?

**Comment by itn3000** [comment]
MessagePipe.csproj+netstandard2.0 and MessagePipe.csproj+net5.0 seem to execute PostBuildUnity(inspected from msbuild log).
I tested `SkipUnchangedFiles=false`, it seems to depend on `-maxCpuCount` parameter(if maxCpuCount=1, replacement works correctry).
`dotnet build` seems to attempt parallel build by default(it may depend on system cpu?).

**Comment by itn3000** [comment]
Oh, sorry, it seems to only depend on parallel build num(if maxcpucount=1, problem did not appear even if `SkipUnchangedFiles=true`).

**Comment by itn3000** [comment]
This seems to be fixed by #64, closing.
