### ISSUE TITLE
[Question] Is it possible to use IMediator instead of IAsyncRequest<TRequest, TResponse> as outlined in Microsoft Docs and MediatR

### ISSUE THREAD

**Issue by jeffward01** [Cysharp/MessagePipe#74]
Hello!

First of all, thank you for the amazing libraries, they are very fast and easy to work with. I plan to use your libraries as much as possible. I will also submit pull requests when I create new features.

I have a use case where I have one class, `IAbsoluteFilePath` that can call many services such as:

`IAbsoluteFileDeleteService`
`IAbsoluteFileCopyService`
`IAbsoluteFileMoveService`

For the above scenerio, using the library it will look something like this:

````csharp

public interface IAbsoluteFilePath { }

// Services
public interface IAbsoluteFileDeleteService { }

public class AbsoluteFileDeleteRequest{}
public class AbsoluteFileDeleteResponse { }

public interface IAbsoluteFileCopyService { }

public class AbsoluteFileCopyRequest { }
public class AbsoluteFileCopyResponse { }



public interface IAbsoluteFileMoveService { }

public class AbsoluteFileMoveRequest { }
public class AbsoluteFileMoveResponse { }




// What the library instructs me to do
public class AbsoluteFilePath : IAbsoluteFilePath
{

  private  readonly IRequestHandler<AbsoluteFileDeleteRequest, AbsoluteFileDeleteResponse> _deleteHandler;
  private readonly IRequestHandler<AbsoluteFileCopyRequest, AbsoluteFileCopyResponse> _copyHandler;
  private readonly IRequestHandler<AbsoluteFileMoveRequest, AbsoluteFileMoveResponse> _moveHandler;
 

    public AbsoluteFilePath(
        IRequestHandler<AbsoluteFileDeleteRequest, AbsoluteFileDeleteResponse> deleteHandler, 
        IRequestHandler<AbsoluteFileCopyRequest, AbsoluteFileCopyResponse> copyHandler,
        IRequestHandler<AbsoluteFileMoveRequest, AbsoluteFileMoveResponse> moveHandler)
    {
        this._deleteHandler = deleteHandler;
        this._copyHandler = copyHandler;
        this._moveHandler = moveHandler;
    }
}

````

Above can become messy very quickly, in addition, if I have 15 services, I will need to inject all 15 services each time, and this can hurt performance.

I would like to do something like this:

````csharp

public interface IMediator {}

// What I want to do
public class AbsoluteFilePathV2 : IAbsoluteFilePath
{

    private readonly IMediator _mediator;

    public AbsoluteFilePathV2(IMediator mediator)
    {
        this._mediator = mediator;
    }
}

````

-----

The documentation on the `MessagePipe` library [claims this is possible](https://github.com/Cysharp/MessagePipe#:~:text=For%20more%20complex%20implementation%20patterns%2C%20this%20Microsoft%20documentation%20is%20applicable.) and requests that I review the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api#implement-the-command-process-pipeline-with-a-mediator-pattern-mediatr) 

From `MessagePipe` Docs:

![image](https://user-images.githubusercontent.com/12589359/155906047-4e136c02-2b2a-4feb-ba16-8d6d7ddada52.png)

The issue is, the `MediaR` and Microsoft documentation has these classes below, while `MessagePipe` is missing these similar classes:

* `IMediator`
* `IRequest`

---

# Question

How can I accomplish this below using `MessagePipe`? 

````csharp

public interface IMediator {}

// What I want to do
public class AbsoluteFilePathV2 : IAbsoluteFilePath
{

    private readonly IMediator _mediator;

    public AbsoluteFilePathV2(IMediator mediator)
    {
        this._mediator = mediator;
    }
}

````

Thanks

**Comment by neuecc** [comment]
I do not like that pattern.
It's just a shorthand of ServiceProvider (IMediator.Send() is  `IServiceProvide.GetRequiredServices<IAsyncRequestHandler<TReq,TRes>>().InvokeAsync(TReq)`)

In other words, if you receive an IServiceProvider, it will be similar.
