### ISSUE TITLE
Keyless `IDistributedPub/Sub` ?

### ISSUE THREAD

**Issue by ogiesen** [Cysharp/MessagePipe#80]
Maybe(/probably) I'm missing something but I'm not quite sure why `IDistributedPub/Sub` forces me to specify a key?

I'm using this with named pipes for direct IPC between a windowless backgound service application and a desktop agent, both running on the same machine. Currently, I'm just passing the pipe name as the key but I really don't need it for anything...

Could a keyless `IDistributedPub/Sub<T>` be added or are there any arguments against it?

**Comment by neuecc** [comment]
I implemented it for network(especially redis) at first.
Therefore, it was only natural that a KEY was needed.
I feel that keyless is difficult as a common interface.
