### ISSUE TITLE
Publish Debug Symbols

### ISSUE THREAD

**Issue by loligans** [Cysharp/MessagePipe#92]
I am unable to load the debug symbols for `MessagePipe` using the default NuGet and Microsoft symbol server

```log
* Searching for 'MessagePipe.pdb' on the configured symbol servers........
Loaded '/home/<omitted>/Workspace/Playground/MMPack/MMPack.Client/bin/Debug/net7.0/MessagePipe.dll'. Cannot find or open the PDB file.
* Searching for 'MessagePipe.Interprocess.pdb' on the configured symbol servers...
Loaded '/home/<omitted>/Workspace/Playground/MMPack/MMPack.Client/bin/Debug/net7.0/MessagePipe.Interprocess.dll'. Cannot find or open the PDB file.
Loaded '/home/<omitted>/Workspace/Playground/MMPack/MMPack.Client/bin/Debug/net7.0/MessagePack.dll'. Symbols loaded.
Loaded '/home/<omitted>/Workspace/Playground/MMPack/MMPack.Client/bin/Debug/net7.0/MessagePack.Annotations.dll'. Symbols loaded.
```

**Comment by neuecc** [comment]
I don't think pdb is usually included, at least not in NuGet.

**Comment by loligans** [comment]
Nope they aren't. However I think it would be good to set up Source Link so that the code can be stepped through. That way developers who don't understand why their integration with MessagePipe isn't working they can step through MessagePipe as well

**Comment by neuecc** [comment]
I am interested in Source Link and will try it sometime soon.
https://github.com/dotnet/sourcelink
